apiVersion: apps/v1
kind: Deployment
metadata:
  name: whisperx
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "whisperx.labels" . | nindent 4 }}
    app.kubernetes.io/name: whisperx
    app.kubernetes.io/instance: whisperx
spec:
  {{- if not .Values.whisperx.autoscaling.enabled }}
  replicas: {{ .Values.whisperx.replicaCount }}
  {{- end }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: whisperx
      app.kubernetes.io/instance: whisperx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: whisperx
        app.kubernetes.io/instance: whisperx
        {{- include "whisperx.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "{{ .Values.readinessProbe.httpGet.port }}"
        prometheus.io/scheme: "http"
        {{- if .Values.pprof.enabled }}
        profiles.grafana.com/memory.scrape: "true"
        profiles.grafana.com/memory.port: "{{ .Values.readinessProbe.httpGet.port }}"
        profiles.grafana.com/cpu.scrape: "true"
        profiles.grafana.com/cpu.port: "{{ .Values.readinessProbe.httpGet.port }}"
        profiles.grafana.com/goroutine.scrape: "true"
        profiles.grafana.com/goroutine.port: "{{ .Values.readinessProbe.httpGet.port }}"
        {{- end }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "whisperx.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: whisperx
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.whisperx.image.repository }}:{{ .Values.whisperx.image.tag | default "whisperx" }}"
          imagePullPolicy: {{ .Values.whisperx.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          {{- with .Values.extraEnv }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.httpGet.path }}
              port: {{ .Values.livenessProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.httpGet.path }}
              port: {{ .Values.readinessProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          resources:
            {{- toYaml .Values.whisperx.resources | nindent 12 }}
      {{- with .Values.whisperx.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.whisperx.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.whisperx.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
